### ISSUE TITLE
No p gain specified for pid

### ISSUE THREAD

**Issue by Wurmi1010** [erdalpekel/panda_simulation#9]
Hello @erdalpekel,

the simulation and the gazebo integration works fine now. But I am getting this error for every joint(panda_joint1, panda_joint2, etc.), that I didn't specify pid gains. Upon launching the simulation I get this error:

`[ERROR] [1584377149.867905243, 0.071000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/panda_joint1`

I could of course just specify any pid gains like this [thread](https://answers.gazebosim.org//question/5468/gazebo_ros_pkgs-no-p-gain-specified-for-pid-in-positionjointinterface/) suggests. But I'm not entirely sure if I would be doing the right thing, because I'm not an engineer and thus not having much knowledge of the parameters.

Do you also get this error? Should I just ignore it or is it important for the simulation in Gazebo?

Best regards,
Christian

**Comment by erdalpekel** [comment]
Hi @Wurmi1010 

I received numerous requests about this issue.
The reason why we are not specifying those parameters is that we want to use the Gazebo internal joint position controller, not the PID controller.

If you were to specify those parameters in the following way:

```
panda:

...

    gazebo_ros_control:
        pid_gains:
            panda_joint1: { p: 10000 }
            panda_joint2: { p: 10000 }
            panda_joint3: { p: 10000 }
            panda_joint4: { p: 10000 }
            panda_joint5: { p: 10000 }
            panda_joint6: { p: 10000 }
            panda_joint7: { p: 10000 }
```

The robot would start wobbling again because PID control requires careful parameter tuning.

To sum up: Just ignore that warning / error.
